### ISSUE TITLE
(Not really an issue, more like fan mail!) Your README is so wonderful!

### ISSUE THREAD

**Issue by sjarva** [anaiel/anaiel#1]
Hi,

Since GitHub doesn't have DMs and you didn't have a public email, I thought that this is one way to send you ~~feedback~~ fan mail 🙈

I just wanted to say that I love the illustration and the badges in the README! 😍💖 It's super short but informative, and one of the most personal and memorable ones I've seen in GitHub. 
(And the badges are so cool I have to add them to my README too.)

P.S. Just close this issue once you've read it 😊

**Comment by anaiel** [comment]
Oh my god I just saw your comment, 3 years later, just as I was about to update my README 🙈 Thank you so much, it still means a lot :)
